### ISSUE TITLE
Instability within the database in master branch

### ISSUE THREAD

**Issue by jayfeather31** [jspauldo98/smart_stock#5]
While I am aware that the master branch will be updated via a development shift into master, the current database system on file for the master branch is, as of this moment, incredibly unstable, and registration may sometimes fail, let alone login being able to gain access to the database at points.

Given that I am unsure if this also applies to the development branch as well, I would recommend that this get resolved, and to assure that the development branch's database system is not outright as unstable, as this will affect testing down the line.

**Comment by jspauldo98** [comment]
The issue is that for Spencer when a user is registered only the Credential table is written to while for Jared and Stefan tables User, PII, and Credential are written to, as they should be. The error Spencer is experiencing is triggered in UserPrivider.cs InsertUser().
